Bump Sarif.Sdk from 4.2.2 to 4.3.0 (#11415)
Bumps [Sarif.Sdk](https://github.com/Microsoft/sarif-sdk) from 4.2.2 to
4.3.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/microsoft/sarif-sdk/blob/main/ReleaseHistory.md">Sarif.Sdk's
changelog</a>.</em></p>
<blockquote>
<h2><strong>v4.3.0</strong> <a
href="https://www.nuget.org/packages/Sarif.Sdk/v4.3.0">Sdk</a> | <a
href="https://www.nuget.org/packages/Sarif.Driver/v4.3.0">Driver</a> |
<a
href="https://www.nuget.org/packages/Sarif.Converters/v4.3.0">Converters</a>
| <a
href="https://www.nuget.org/packages/Sarif.Multitool/v4.3.0">Multitool</a>
| <a
href="https://www.nuget.org/packages/Sarif.Multitool.Library/v4.3.0">Multitool
Library</a></h2>
<ul>
<li>
<p>BUG: Resolve <code>NullReferenceException</code> retrieving
<code>MultithreadedZipArchiveArtifactProvider.SizeInBytes</code> after
content have been faulted in.</p>
</li>
<li>
<p>BUG: Improve HDF-&gt;SARIF conversion to properly map various
properties (e.g., <code>kind</code>, <code>level</code>,
<code>rank</code>) and generally prepare the converted SARIF for
ingestion to <a
href="https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning">GitHub
Advanced Security</a>.</p>
</li>
</ul>
<h2><strong>v4.2.1</strong> <a
href="https://www.nuget.org/packages/Sarif.Sdk/4.2.1">Sdk</a> | <a
href="https://www.nuget.org/packages/Sarif.Driver/4.2.1">Driver</a> | <a
href="https://www.nuget.org/packages/Sarif.Converters/4.2.1">Converters</a>
| <a
href="https://www.nuget.org/packages/Sarif.Multitool/4.2.1">Multitool</a>
| <a
href="https://www.nuget.org/packages/Sarif.Multitool.Library/4.2.1">Multitool
Library</a></h2>
<ul>
<li>BUG: Resolve <code>NotSupportedException</code> thrown (on .NET 4.8
and earlier) on accessing <code>DeflateStream.Length</code> from
<code>MultithreadedZipArchiveArtifactProvider.SizeInBytes</code>
property.</li>
</ul>
<h2><strong>v4.2.0</strong> <a
href="https://www.nuget.org/packages/Sarif.Sdk/4.2.0">Sdk</a> | <a
href="https://www.nuget.org/packages/Sarif.Driver/4.2.0">Driver</a> | <a
href="https://www.nuget.org/packages/Sarif.Converters/4.2.0">Converters</a>
| <a
href="https://www.nuget.org/packages/Sarif.Multitool/4.2.0">Multitool</a>
| <a
href="https://www.nuget.org/packages/Sarif.Multitool.Library/4.2.0">Multitool
Library</a></h2>
<ul>
<li>BRK: Change <code>ArtifactProvicer.SizeInBytes</code> property type
from <code>ulong</code> to <code>long</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2675">#2675</a></li>
<li>BRK: Update <code>SarifLog.Post(Uri, StreamWriter,
HttpClient)</code> return value to <code>HttpResponseMessage</code> (to
make returned correlation id and error messages available). <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2672">#2672</a></li>
<li>BRK: <code>RuntimeConditions</code> now of type <code>long</code> to
permit more flag values. Many literal values have changed for individual
members. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2660">#2660</a></li>
<li>BRK: <code>RuntimeConditions.OneOrMoreFilesSkippedDueToSize</code>
renamed to <code>OneOrMoreFilesSkippedDueToExceedingSizeLimits</code>.
<a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2660">#2660</a></li>
<li>BRK: <code>Notes.LogFileSkippedDueToSize</code> renamed to
<code>LogFileExceedingSizeLimitSkipped</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2660">#2660</a></li>
<li>BRK: Command-line argument <code>automationGuid</code> renamed to
<code>automation-guid</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2647">#2647</a></li>
<li>BRK: Command-line argument <code>automationId</code> renamed to
<code>automation-id</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2647">#2647</a></li>
<li>BRK: Update <code>AnalyzeOptionsBase</code> <code>Quiet</code>,
<code>Recurse</code>, <code>LogEnvironment</code>, and
<code>RichReturnCode</code> properties to bool? type. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2644">#2644</a></li>
<li>BRK: Rename <code>Errors.LogExceptionCreatingLogFile</code> to
<code>Errors.LogExceptionCreatingOutputFile</code> to reflect its
general purpose. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2643">#2643</a></li>
<li>BRK: Add <code>IAnalysisContext.FileRegionsCache</code> property.
Used for data sharing across analysis phases. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2642">#2642</a></li>
<li>BRK: Remove <code>FileRegionsCache.Instance</code> singleton object.
Analysis should always prefer context file region context instead. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2642">#2642</a></li>
<li>BRK: <code>fileRegionsCache</code> parameter is now required for the
<code>InsertOptionalDataVisitor</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2642">#2642</a></li>
<li>BRK: Add <code>IAnalysisLogger.TargetAnalysisComplete</code> method.
<a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2637">#2637</a></li>
<li>BRK: Remove unused <code>quiet</code> parameter from
<code>SarifLogger</code>. [#2639]<a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">microsoft/sarif-sdk#2639</a></li>
<li>BRK: Remove <code>ComputeHashData</code> and
<code>AnalysisTargetToHashDataMap</code> properties from
<code>SarifLogger</code> (in preference of new
<code>fileRegionsCache</code> parameter. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">#2639</a></li>
<li>BRK: Eliminate proactive hashing of artifacts in
<code>SarifLogger</code> constructor when
<code>OptionallyEmittedData.Hashes</code> is specified. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">#2639</a></li>
<li>BUG: Provider better size return values for in-memory
<code>EnumeratedArtifact</code> instances. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2674">#2674</a></li>
<li>BUG: Fixed <code>ERR999.UnhandledEngineException:
System.InvalidOperationException: This operation is not supported for a
relative URI</code> when running in Linux with files skipped due to zero
byte size. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2664">#2664</a></li>
<li>BUG: Properly report skipping empty files (rather than reporting
file was skipped due to exceeding size limits). <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2660">#2660</a></li>
<li>BUG: Update user messages and code comments that refer to
<code>--force</code> (replaced by <code>--log ForceOverwrite</code>). <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2656">#2656</a></li>
<li>BUG: Handle return code 422 <code>UnprocessableEntity</code> when
validating that log file POST endpoint is available. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2656">#2656</a></li>
<li>BUG: Eliminate erroneous <code>Posted log file successfully</code>
message when context <code>PostUri</code> is non-null but empty. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2655">#2655</a></li>
<li>BUG: Resolves <code>IOException</code> raised by calling
<code>FileSystem.ReadAllText</code> on file locked for write (but not
read). <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2655">#2655</a></li>
<li>BUG: Correct <code>toolComponent.language</code> regex in JSON
schema. [#2653]<a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2653">microsoft/sarif-sdk#2653</a></li>
<li>BUG: Generate <code>IAnalysisLogger.AnalyzingTarget</code> callbacks
from <code>MulthreadedAnalyzeCommandBase</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2637">#2637</a></li>
<li>BUG: Persist <code>fileRegionsCache</code> parameter in
<code>SarifLogger</code> to support retrieving hash data. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">#2639</a></li>
<li>BUG: Allow override of <code>FailureLevels</code> and
<code>ResultKinds</code> in context objects. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">#2639</a></li>
<li>NEW: Add general <code>Notes.LogFileSkipped</code> notification
mechanism for any skipped files. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2675">#2675</a></li>
<li>NEW: Add 50K files to analysis channel (rather than previous value
of 25k). Smooths performance analyzing many small artifacts. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2674">#2674</a></li>
<li>NEW: Provide new ETW telemetry for runtime behavior, provider
<code>SarifDriver</code>, guid
<code>c84480b4-a77f-421f-8a11-48210c1724d4</code>. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2668">microsoft/sarif-sdk#2668</a></li>
<li>NEW: Provide convenience enumerator at the <code>SarifLog</code>
level that iterates over all results in all runs in the log. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2660">#2660</a></li>
<li>NEW: Provide <code>Notes.LogEmptyFileSkipped</code> helper for
reporting zero-byte files skipped at scan time. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2660">#2660</a></li>
<li>NEW: Add <code>MemoryStreamSarifLogger</code> (for in-memory SARIF
generation). <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2655">#2655</a></li>
<li>NEW: Add <code>AnalyzeContext.VersionControlProvenance</code>
property. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2646">#2646</a></li>
<li>NEW: Add <code>DefaultTraces.ResultsSummary</code> property that
drives naive results summary in console logger. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2643">#2643</a></li>
<li>NEW: Prove <code>AnalyzeContextBase.Inline</code> helper. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2643">#2643</a></li>
<li>NEW: <code>SarifLogger.FileRegionsCache</code> property added (to
support sharing this instance with context and other classes). <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2642">#2642</a></li>
<li>NEW: <code>MultithreadedAnalyzeCommandBase.Tool</code> is now public
to support in-memory analysis (and logging) of targets. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">#2639</a></li>
<li>NEW: Add <code>DefaultTraces.TargetsScanned</code> which is used by
<code>ConsoleLogger</code> to emit target start and stop analysis
messages. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2637">#2637</a></li>
<li>NEW: Update <code>FileRegionsCache</code> to retrieve cached newline
indices and hash data via <code>GetNewLineIndex</code> and
<code>GetHashData</code> methods. <a
href="https://redirect.github.com/microsoft/sarif-sdk/pull/2639">#2639</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/Microsoft/sarif-sdk/commits">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=Sarif.Sdk&package-manager=nuget&previous-version=4.2.2&new-version=4.3.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>
###### Microsoft Reviewers:
codeflow:open?pullrequest=https://github.com/Azure/bicep/pull/11415&drop=dogfoodAlpha

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Anthony Martin <38542602+anthony-c-martin@users.noreply.github.com>