Enable Microsoft.VisualStudio.Threading analyzers (#11533)
This would have made things easier for devs in a recent PR.

With this change, the PR now gets:
```
bicep\src\Bicep.Core\Registry\OciModuleRegistry.cs(323,39): error CS1998: This async method lack
s 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or
 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\stephwe\repos\bicep\src\Bicep.Core\Bicep.
Core.csproj]
bicep\src\Bicep.Core\Registry\OciModuleRegistry.cs(323,39): error VSTHRD100: Avoid "async void"
methods, because any exceptions not handled by the method will crash the process [C:\Users\stephwe\repos\bicep\src\Bice
p.Core\Bicep.Core.csproj]
```
###### Microsoft Reviewers:
codeflow:open?pullrequest=https://github.com/Azure/bicep/pull/11533&drop=dogfoodAlpha